// File generated by FlutterFire CLI (copied from WasteJustice template project).
// Re-run `flutterfire configure` for this app if you use a separate Firebase project.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'run `flutterfire configure` for this project.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGOQgqAwFmXysHJeuR1MLxBOaOktdx9Dk',
    appId: '1:697041967063:web:f9bbaf0b756508f90ddd92',
    messagingSenderId: '697041967063',
    projectId: 'wastejustice-9620d',
    authDomain: 'wastejustice-9620d.firebaseapp.com',
    storageBucket: 'wastejustice-9620d.firebasestorage.app',
    measurementId: 'G-HGNL30NNCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV41VI_eNNzwe1GDaLIrnYeNOMngoSoKA',
    appId: '1:697041967063:android:7b61f7e5f245fa3c0ddd92',
    messagingSenderId: '697041967063',
    projectId: 'wastejustice-9620d',
    storageBucket: 'wastejustice-9620d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmVV871O98ZME501ektovAbt904izpdUc',
    appId: '1:697041967063:ios:b6059ded7db234d70ddd92',
    messagingSenderId: '697041967063',
    projectId: 'wastejustice-9620d',
    storageBucket: 'wastejustice-9620d.firebasestorage.app',
    iosBundleId: 'com.tshijuka.documentSeeker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmVV871O98ZME501ektovAbt904izpdUc',
    appId: '1:697041967063:ios:b6059ded7db234d70ddd92',
    messagingSenderId: '697041967063',
    projectId: 'wastejustice-9620d',
    storageBucket: 'wastejustice-9620d.firebasestorage.app',
    iosBundleId: 'com.tshijuka.documentSeeker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGOQgqAwFmXysHJeuR1MLxBOaOktdx9Dk',
    appId: '1:697041967063:web:bf9147793a4b28280ddd92',
    messagingSenderId: '697041967063',
    projectId: 'wastejustice-9620d',
    authDomain: 'wastejustice-9620d.firebaseapp.com',
    storageBucket: 'wastejustice-9620d.firebasestorage.app',
    measurementId: 'G-TER7658TP8',
  );
}
